# Generated by Django 2.0.5 on 2018-05-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='file_last_modified',
            field=models.CharField(max_length=100),
        ),
    ]
