# Generated by Django 2.0.5 on 2018-05-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notary', '0002_auto_20180522_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='transaction_hash',
            field=models.CharField(default='', max_length=256),
        ),
    ]
